# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.risk.hazard_weights:
        heat: 1.0
        flood: 1.2
        drought_clay: 0.9
        cavites: 0.8
    app.risk.thresholds:
        low: 25
        medium: 50
        high: 75
    app.geocoding.base_url: '%env(default::GEOCODING_BASE_URL)%'
    app.georisques.flood_frequent_layer: '%env(default::GEORISQUES_FLOOD_FREQUENT_LAYER_URL)%'
    app.georisques.flood_medium_layer: '%env(default::GEORISQUES_FLOOD_MEDIUM_LAYER_URL)%'
    app.georisques.flood_rare_layer: '%env(default::GEORISQUES_FLOOD_RARE_LAYER_URL)%'
    app.georisques.rga_layer: '%env(default::GEORISQUES_RGA_LAYER_URL)%'
    app.georisques.cavites_layer: '%env(default::GEORISQUES_CAVITES_LAYER_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\RiskDataProviderInterface:
            tags: ['app.risk_provider']

    App\Service\RiskScoringService:
        arguments:
            $hazardWeights: '%app.risk.hazard_weights%'
            $thresholds: '%app.risk.thresholds%'

    App\Service\AuditOrchestrator:
        arguments:
            $providers: !tagged_iterator app.risk_provider

    App\Service\GeocodingServiceInterface:
        class: App\Service\IgnGeocodingService
        arguments:
            $baseUrl: '%app.geocoding.base_url%'

    App\Service\ArcGisRiskClient: ~

    App\Service\Provider\FloodRiskProvider:
        arguments:
            $frequentLayerUrl: '%app.georisques.flood_frequent_layer%'
            $mediumLayerUrl: '%app.georisques.flood_medium_layer%'
            $rareLayerUrl: '%app.georisques.flood_rare_layer%'

    App\Service\Provider\DroughtClayRiskProvider:
        arguments:
            $layerUrl: '%app.georisques.rga_layer%'

    App\Service\Provider\CavitesRiskProvider:
        arguments:
            $layerUrl: '%app.georisques.cavites_layer%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
